web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
  env_file:
    - '.env.web'
db:
  image: library/mysql:8
  ports:
    - "13306:3306"
  environment:
      - MYSQL_ROOT_PASSWORD=root

